//

module.exports = [
   [
      327,
      0,
      true,
      "woman hair 00",
      "hair",
      0,
      0,
      0,
      6167,
      [
         12501,
         "hero_item_human_warrior_hair_hair_woman_00__avatar_hair_back_lay01_c2"
      ],
      [
         12503,
         "hero_item_human_warrior_hair_hair_woman_00__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      329,
      1,
      true,
      "woman hair 01",
      "hair",
      0,
      0,
      0,
      6169,
      [
         12505,
         "hero_item_human_warrior_hair_hair_woman_01__avatar_hair_back_lay01_c2"
      ],
      [
         12507,
         "hero_item_human_warrior_hair_hair_woman_01__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      331,
      2,
      true,
      "woman hair 02",
      "hair",
      0,
      0,
      0,
      6171,
      [
         12509,
         "hero_item_human_warrior_hair_hair_woman_02__avatar_hair_back_lay01_c2"
      ],
      [
         12511,
         "hero_item_human_warrior_hair_hair_woman_02__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      333,
      3,
      true,
      "woman hair 03",
      "hair",
      0,
      0,
      0,
      6173,
      [
         12513,
         "hero_item_human_warrior_hair_hair_woman_03__avatar_hair_back_lay01_c2"
      ],
      [
         12515,
         "hero_item_human_warrior_hair_hair_woman_03__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      335,
      4,
      true,
      "woman hair 04",
      "hair",
      0,
      0,
      0,
      6175,
      [
         12517,
         "hero_item_human_warrior_hair_hair_woman_04__avatar_hair_back_lay01_c2"
      ],
      [
         12519,
         "hero_item_human_warrior_hair_hair_woman_04__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      337,
      5,
      true,
      "woman hair 05",
      "hair",
      0,
      0,
      0,
      6177,
      [
         12521,
         "hero_item_human_warrior_hair_hair_woman_05__avatar_hair_back_lay01_c2"
      ],
      [
         12523,
         "hero_item_human_warrior_hair_hair_woman_05__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      339,
      6,
      true,
      "woman hair 06",
      "hair",
      0,
      0,
      0,
      6179,
      [
         12525,
         "hero_item_human_warrior_hair_hair_woman_06__avatar_hair_back_lay01_c2"
      ],
      [
         12527,
         "hero_item_human_warrior_hair_hair_woman_06__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      341,
      7,
      true,
      "woman hair 07",
      "hair",
      0,
      0,
      0,
      6181,
      [
         12529,
         "hero_item_human_warrior_hair_hair_woman_07__avatar_hair_back_lay01_c2"
      ],
      [
         12531,
         "hero_item_human_warrior_hair_hair_woman_07__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      343,
      8,
      true,
      "woman hair 08",
      "hair",
      0,
      0,
      0,
      6183,
      [
         12533,
         "hero_item_human_warrior_hair_hair_woman_08__avatar_hair_back_lay01_c2"
      ],
      [
         12535,
         "hero_item_human_warrior_hair_hair_woman_08__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      345,
      10,
      true,
      "woman hair 10",
      "hair",
      0,
      0,
      0,
      6185,
      [
         12539,
         "hero_item_human_warrior_hair_hair_woman_10__avatar_hair_back_lay01_c2"
      ],
      [
         12541,
         "hero_item_human_warrior_hair_hair_woman_10__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      347,
      0,
      false,
      "woman eyebrows 00",
      "eyebrows",
      0,
      0,
      0,
      6045
   ],
   [
      349,
      1,
      false,
      "woman eyebrows 01",
      "eyebrows",
      0,
      0,
      0,
      6047,
      [
         11905,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_01__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      351,
      2,
      false,
      "woman eyebrows 02",
      "eyebrows",
      0,
      0,
      0,
      6049,
      [
         11907,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_02__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      353,
      4,
      false,
      "woman eyebrows 04",
      "eyebrows",
      0,
      0,
      0,
      6053,
      [
         11911,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_04__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      355,
      5,
      false,
      "woman eyebrows 05",
      "eyebrows",
      0,
      0,
      0,
      6055,
      [
         11913,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_05__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      357,
      6,
      false,
      "woman eyebrows 06",
      "eyebrows",
      0,
      0,
      0,
      6057,
      [
         11915,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_06__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      359,
      1,
      false,
      "woman eyes 01",
      "eyes",
      0,
      0,
      0,
      6077,
      [
         13921,
         "hero_item_human_warrior_eyes_eyes_woman_01__avatar_eyes_lay40"
      ]
   ],
   [
      361,
      2,
      false,
      "woman eyes 02",
      "eyes",
      0,
      0,
      0,
      6079,
      [
         13923,
         "hero_item_human_warrior_eyes_eyes_woman_02__avatar_eyes_lay40"
      ]
   ],
   [
      363,
      3,
      false,
      "woman eyes 03",
      "eyes",
      0,
      0,
      0,
      6081,
      [
         13925,
         "hero_item_human_warrior_eyes_eyes_woman_03__avatar_eyes_lay40"
      ]
   ],
   [
      365,
      4,
      false,
      "woman eyes 04",
      "eyes",
      0,
      0,
      0,
      6083,
      [
         13927,
         "hero_item_human_warrior_eyes_eyes_woman_04__avatar_eyes_lay40"
      ]
   ],
   [
      367,
      5,
      false,
      "woman eyes 05",
      "eyes",
      0,
      0,
      0,
      6085,
      [
         13929,
         "hero_item_human_warrior_eyes_eyes_woman_05__avatar_eyes_lay40"
      ]
   ],
   [
      369,
      6,
      false,
      "woman eyes 06",
      "eyes",
      0,
      0,
      0,
      6087,
      [
         13931,
         "hero_item_human_warrior_eyes_eyes_woman_06__avatar_eyes_lay40"
      ]
   ],
   [
      371,
      7,
      false,
      "woman eyes 07",
      "eyes",
      0,
      0,
      0,
      6089,
      [
         13933,
         "hero_item_human_warrior_eyes_eyes_woman_07__avatar_eyes_lay40"
      ]
   ],
   [
      373,
      8,
      false,
      "woman eyes 08",
      "eyes",
      0,
      0,
      0,
      6091,
      [
         13935,
         "hero_item_human_warrior_eyes_eyes_woman_08__avatar_eyes_lay40"
      ]
   ],
   [
      375,
      9,
      false,
      "woman eyes 09",
      "eyes",
      0,
      0,
      0,
      6093,
      [
         11977,
         "hero_item_human_warrior_eyes_eyes_woman_09__avatar_eyes_lay40"
      ]
   ],
   [
      377,
      10,
      false,
      "woman eyes 10",
      "eyes",
      0,
      0,
      0,
      6095,
      [
         11979,
         "hero_item_human_warrior_eyes_eyes_woman_10__avatar_eyes_lay40"
      ]
   ],
   [
      379,
      11,
      false,
      "woman eyes 11",
      "eyes",
      0,
      0,
      0,
      6097,
      [
         11981,
         "hero_item_human_warrior_eyes_eyes_woman_11__avatar_eyes_lay40"
      ]
   ],
   [
      381,
      12,
      false,
      "woman eyes 12",
      "eyes",
      0,
      0,
      0,
      6099,
      [
         11983,
         "hero_item_human_warrior_eyes_eyes_woman_12__avatar_eyes_lay40"
      ]
   ],
   [
      383,
      13,
      false,
      "woman eyes 13",
      "eyes",
      0,
      0,
      0,
      6101,
      [
         11985,
         "hero_item_human_warrior_eyes_eyes_woman_13__avatar_eyes_lay40"
      ]
   ],
   [
      385,
      14,
      false,
      "woman eyes 14",
      "eyes",
      0,
      0,
      0,
      6103,
      [
         11987,
         "hero_item_human_warrior_eyes_eyes_woman_14__avatar_eyes_lay40"
      ]
   ],
   [
      387,
      15,
      false,
      "woman eyes 15",
      "eyes",
      0,
      0,
      0,
      6105,
      [
         11989,
         "hero_item_human_warrior_eyes_eyes_woman_15__avatar_eyes_lay40"
      ]
   ],
   [
      389,
      1,
      false,
      "woman face 01",
      "nose",
      0,
      0,
      0,
      6107,
      [
         12067,
         "hero_item_human_warrior_face_face_woman_01__avatar_face_lay20_c1"
      ]
   ],
   [
      409,
      0,
      false,
      "woman special 00",
      "facespecial",
      0,
      0,
      0,
      6247,
      [
         12925,
         "hero_item_human_warrior_special_special_woman_00__avatar_special_lay50_c1"
      ]
   ],
   [
      411,
      1,
      false,
      "woman special 01",
      "facespecial",
      0,
      0,
      0,
      6249,
      [
         12927,
         "hero_item_human_warrior_special_special_woman_01__avatar_special_lay50_c1"
      ]
   ],
   [
      413,
      2,
      false,
      "woman special 02",
      "facespecial",
      0,
      0,
      0,
      6251,
      [
         12935,
         "hero_item_human_warrior_special_special_woman_02__avatar_special_lay50_c1"
      ]
   ],
   [
      453,
      11,
      true,
      "woman hair 11",
      "hair",
      0,
      0,
      0,
      6187,
      [
         12543,
         "hero_item_human_warrior_hair_hair_woman_11__avatar_hair_back_lay01_c2"
      ],
      [
         12545,
         "hero_item_human_warrior_hair_hair_woman_11__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      455,
      12,
      true,
      "woman hair 12",
      "hair",
      0,
      0,
      0,
      6189,
      [
         12547,
         "hero_item_human_warrior_hair_hair_woman_12__avatar_hair_back_lay01_c2"
      ],
      [
         12549,
         "hero_item_human_warrior_hair_hair_woman_12__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      457,
      13,
      true,
      "woman hair 13",
      "hair",
      0,
      0,
      0,
      6191,
      [
         12551,
         "hero_item_human_warrior_hair_hair_woman_13__avatar_hair_back_lay01_c2"
      ],
      [
         12553,
         "hero_item_human_warrior_hair_hair_woman_13__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      459,
      14,
      true,
      "woman hair 14",
      "hair",
      0,
      0,
      0,
      6193,
      [
         12555,
         "hero_item_human_warrior_hair_hair_woman_14__avatar_hair_back_lay01_c2"
      ],
      [
         12557,
         "hero_item_human_warrior_hair_hair_woman_14__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      461,
      15,
      true,
      "woman hair 15",
      "hair",
      0,
      0,
      0,
      6195,
      [
         12559,
         "hero_item_human_warrior_hair_hair_woman_15__avatar_hair_back_lay01_c2"
      ],
      [
         12561,
         "hero_item_human_warrior_hair_hair_woman_15__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      463,
      16,
      true,
      "woman hair 16",
      "hair",
      0,
      0,
      0,
      6197,
      [
         12563,
         "hero_item_human_warrior_hair_hair_woman_16__avatar_hair_back_lay01_c2"
      ],
      [
         12565,
         "hero_item_human_warrior_hair_hair_woman_16__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      465,
      17,
      true,
      "woman hair 17",
      "hair",
      0,
      0,
      0,
      6199,
      [
         12567,
         "hero_item_human_warrior_hair_hair_woman_17__avatar_hair_back_lay01_c2"
      ],
      [
         12569,
         "hero_item_human_warrior_hair_hair_woman_17__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      467,
      18,
      true,
      "woman hair 18",
      "hair",
      0,
      0,
      0,
      6201,
      [
         12571,
         "hero_item_human_warrior_hair_hair_woman_18__avatar_hair_back_lay01_c2"
      ],
      [
         12573,
         "hero_item_human_warrior_hair_hair_woman_18__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      469,
      19,
      true,
      "woman hair 19",
      "hair",
      0,
      0,
      0,
      6203,
      [
         12575,
         "hero_item_human_warrior_hair_hair_woman_19__avatar_hair_back_lay01_c2"
      ],
      [
         12577,
         "hero_item_human_warrior_hair_hair_woman_19__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      471,
      20,
      true,
      "woman hair 20",
      "hair",
      0,
      0,
      0,
      6205,
      [
         12579,
         "hero_item_human_warrior_hair_hair_woman_20__avatar_hair_back_lay01_c2"
      ],
      [
         12581,
         "hero_item_human_warrior_hair_hair_woman_20__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      473,
      21,
      true,
      "woman hair 21",
      "hair",
      0,
      0,
      0,
      6207,
      [
         12583,
         "hero_item_human_warrior_hair_hair_woman_21__avatar_hair_back_lay01_c2"
      ],
      [
         12585,
         "hero_item_human_warrior_hair_hair_woman_21__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      475,
      22,
      true,
      "woman hair 22",
      "hair",
      0,
      0,
      0,
      6209,
      [
         12587,
         "hero_item_human_warrior_hair_hair_woman_22__avatar_hair_back_lay01_c2"
      ],
      [
         12589,
         "hero_item_human_warrior_hair_hair_woman_22__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      477,
      23,
      true,
      "woman hair 23",
      "hair",
      0,
      0,
      0,
      6211,
      [
         12591,
         "hero_item_human_warrior_hair_hair_woman_23__avatar_hair_back_lay01_c2"
      ],
      [
         12593,
         "hero_item_human_warrior_hair_hair_woman_23__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      479,
      24,
      true,
      "woman hair 24",
      "hair",
      0,
      0,
      0,
      6213,
      [
         12595,
         "hero_item_human_warrior_hair_hair_woman_24__avatar_hair_back_lay01_c2"
      ],
      [
         12597,
         "hero_item_human_warrior_hair_hair_woman_24__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      481,
      25,
      true,
      "woman hair 25",
      "hair",
      0,
      0,
      0,
      6215,
      [
         12599,
         "hero_item_human_warrior_hair_hair_woman_25__avatar_hair_back_lay01_c2"
      ],
      [
         12601,
         "hero_item_human_warrior_hair_hair_woman_25__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      483,
      26,
      true,
      "woman hair 26",
      "hair",
      0,
      0,
      0,
      6217,
      [
         12603,
         "hero_item_human_warrior_hair_hair_woman_26__avatar_hair_back_lay01_c2"
      ],
      [
         12605,
         "hero_item_human_warrior_hair_hair_woman_26__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      485,
      27,
      true,
      "woman hair 27",
      "hair",
      0,
      0,
      0,
      6219,
      [
         12607,
         "hero_item_human_warrior_hair_hair_woman_27__avatar_hair_back_lay01_c2"
      ],
      [
         12609,
         "hero_item_human_warrior_hair_hair_woman_27__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      487,
      28,
      true,
      "woman hair 28",
      "hair",
      0,
      0,
      0,
      6221,
      [
         12611,
         "hero_item_human_warrior_hair_hair_woman_28__avatar_hair_back_lay01_c2"
      ],
      [
         12613,
         "hero_item_human_warrior_hair_hair_woman_28__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      489,
      29,
      true,
      "woman hair 29",
      "hair",
      0,
      0,
      0,
      6223,
      [
         12615,
         "hero_item_human_warrior_hair_hair_woman_29__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      491,
      30,
      true,
      "woman hair 30",
      "hair",
      0,
      0,
      0,
      6225,
      [
         12617,
         "hero_item_human_warrior_hair_hair_woman_30__avatar_hair_back_lay01_c2"
      ],
      [
         12619,
         "hero_item_human_warrior_hair_hair_woman_30__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      493,
      31,
      true,
      "woman hair 31",
      "hair",
      0,
      0,
      0,
      6227,
      [
         12621,
         "hero_item_human_warrior_hair_hair_woman_31__avatar_hair_back_lay01_c2"
      ],
      [
         12623,
         "hero_item_human_warrior_hair_hair_woman_31__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      495,
      32,
      true,
      "woman hair 32",
      "hair",
      0,
      0,
      0,
      6229,
      [
         12625,
         "hero_item_human_warrior_hair_hair_woman_32__avatar_hair_back_lay01_c2"
      ],
      [
         12627,
         "hero_item_human_warrior_hair_hair_woman_32__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      497,
      33,
      true,
      "woman hair 33",
      "hair",
      0,
      0,
      0,
      6231,
      [
         12629,
         "hero_item_human_warrior_hair_hair_woman_33__avatar_hair_back_lay01_c2"
      ],
      [
         12631,
         "hero_item_human_warrior_hair_hair_woman_33__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      499,
      34,
      true,
      "woman hair 34",
      "hair",
      0,
      0,
      0,
      6233,
      [
         12633,
         "hero_item_human_warrior_hair_hair_woman_34__avatar_hair_back_lay01_c2"
      ],
      [
         12635,
         "hero_item_human_warrior_hair_hair_woman_34__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      501,
      35,
      true,
      "woman hair 35",
      "hair",
      0,
      0,
      0,
      6235,
      [
         12637,
         "hero_item_human_warrior_hair_hair_woman_35__avatar_hair_back_lay01_c2"
      ],
      [
         12639,
         "hero_item_human_warrior_hair_hair_woman_35__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      503,
      36,
      true,
      "woman hair 36",
      "hair",
      0,
      0,
      0,
      6237,
      [
         12641,
         "hero_item_human_warrior_hair_hair_woman_36__avatar_hair_back_lay01_c2"
      ],
      [
         12643,
         "hero_item_human_warrior_hair_hair_woman_36__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      505,
      37,
      true,
      "woman hair 37",
      "hair",
      0,
      0,
      0,
      6239,
      [
         12645,
         "hero_item_human_warrior_hair_hair_woman_37__avatar_hair_back_lay01_c2"
      ],
      [
         12647,
         "hero_item_human_warrior_hair_hair_woman_37__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      507,
      38,
      true,
      "woman hair 38",
      "hair",
      0,
      0,
      0,
      6241,
      [
         12649,
         "hero_item_human_warrior_hair_hair_woman_38__avatar_hair_back_lay01_c2"
      ],
      [
         12651,
         "hero_item_human_warrior_hair_hair_woman_38__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      509,
      39,
      true,
      "woman hair 39",
      "hair",
      0,
      0,
      0,
      6243,
      [
         12653,
         "hero_item_human_warrior_hair_hair_woman_39__avatar_hair_back_lay01_c2"
      ],
      [
         12655,
         "hero_item_human_warrior_hair_hair_woman_39__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      511,
      40,
      true,
      "woman hair 40",
      "hair",
      0,
      0,
      0,
      6245,
      [
         12657,
         "hero_item_human_warrior_hair_hair_woman_40__avatar_hair_back_lay01_c2"
      ],
      [
         12659,
         "hero_item_human_warrior_hair_hair_woman_40__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      513,
      7,
      false,
      "woman eyebrows 07",
      "eyebrows",
      0,
      0,
      0,
      6059,
      [
         11917,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_07__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      515,
      8,
      false,
      "woman eyebrows 08",
      "eyebrows",
      0,
      0,
      0,
      6061,
      [
         11919,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_08__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      517,
      9,
      false,
      "woman eyebrows 09",
      "eyebrows",
      0,
      0,
      0,
      6063,
      [
         11921,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_09__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      519,
      10,
      false,
      "woman eyebrows 10",
      "eyebrows",
      0,
      0,
      0,
      6065,
      [
         11923,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_10__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      521,
      11,
      false,
      "woman eyebrows 11",
      "eyebrows",
      0,
      0,
      0,
      6067,
      [
         11925,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_11__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      523,
      12,
      false,
      "woman eyebrows 12",
      "eyebrows",
      0,
      0,
      0,
      6069,
      [
         11927,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_12__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      525,
      13,
      false,
      "woman eyebrows 13",
      "eyebrows",
      0,
      0,
      0,
      6071,
      [
         11929,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_13__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      527,
      14,
      false,
      "woman eyebrows 14",
      "eyebrows",
      0,
      0,
      0,
      6073,
      [
         11931,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_14__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      529,
      15,
      false,
      "woman eyebrows 15",
      "eyebrows",
      0,
      0,
      0,
      6075,
      [
         11933,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_15__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      533,
      3,
      false,
      "woman eyebrows 03",
      "eyebrows",
      0,
      0,
      0,
      6051,
      [
         11909,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_03__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      535,
      16,
      false,
      "woman eyebrows 16",
      "eyebrows",
      0,
      0,
      0,
      6315,
      [
         11935,
         "hero_item_human_warrior_eyebrows_eyebrows_woman_16__avatar_eyebrow_lay60_c2"
      ]
   ],
   [
      545,
      9,
      true,
      "woman hair 09",
      "hair",
      0,
      0,
      0,
      6325,
      [
         12537,
         "hero_item_human_warrior_hair_hair_woman_09__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      547,
      41,
      true,
      "woman hair 41",
      "hair",
      0,
      0,
      0,
      6327,
      [
         12661,
         "hero_item_human_warrior_hair_hair_woman_41__avatar_hair_back_lay01_c2"
      ],
      [
         12663,
         "hero_item_human_warrior_hair_hair_woman_41__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      549,
      42,
      true,
      "woman hair 42",
      "hair",
      0,
      0,
      0,
      6329,
      [
         12665,
         "hero_item_human_warrior_hair_hair_woman_42__avatar_hair_back_lay01_c2"
      ],
      [
         12667,
         "hero_item_human_warrior_hair_hair_woman_42__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      551,
      43,
      true,
      "woman hair 43",
      "hair",
      0,
      0,
      0,
      6331,
      [
         12669,
         "hero_item_human_warrior_hair_hair_woman_43__avatar_hair_back_lay01_c2"
      ],
      [
         12671,
         "hero_item_human_warrior_hair_hair_woman_43__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      553,
      44,
      true,
      "woman hair 44",
      "hair",
      0,
      0,
      0,
      6333,
      [
         12673,
         "hero_item_human_warrior_hair_hair_woman_44__avatar_hair_back_lay01_c2"
      ],
      [
         12675,
         "hero_item_human_warrior_hair_hair_woman_44__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      555,
      45,
      true,
      "woman hair 45",
      "hair",
      0,
      0,
      0,
      6335,
      [
         12677,
         "hero_item_human_warrior_hair_hair_woman_45__avatar_hair_back_lay01_c2"
      ],
      [
         12679,
         "hero_item_human_warrior_hair_hair_woman_45__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      557,
      46,
      true,
      "woman hair 46",
      "hair",
      0,
      0,
      0,
      6337,
      [
         12681,
         "hero_item_human_warrior_hair_hair_woman_46__avatar_hair_back_lay01_c2"
      ],
      [
         12683,
         "hero_item_human_warrior_hair_hair_woman_46__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      559,
      47,
      true,
      "woman hair 47",
      "hair",
      0,
      0,
      0,
      6339,
      [
         12685,
         "hero_item_human_warrior_hair_hair_woman_47__avatar_hair_back_lay01_c2"
      ],
      [
         12687,
         "hero_item_human_warrior_hair_hair_woman_47__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      561,
      48,
      true,
      "woman hair 48",
      "hair",
      0,
      0,
      0,
      6341,
      [
         12689,
         "hero_item_human_warrior_hair_hair_woman_48__avatar_hair_back_lay01_c2"
      ],
      [
         12691,
         "hero_item_human_warrior_hair_hair_woman_48__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      563,
      49,
      true,
      "woman hair 49",
      "hair",
      0,
      0,
      0,
      6343,
      [
         12693,
         "hero_item_human_warrior_hair_hair_woman_49__avatar_hair_back_lay01_c2"
      ],
      [
         12695,
         "hero_item_human_warrior_hair_hair_woman_49__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      565,
      50,
      true,
      "woman hair 50",
      "hair",
      0,
      0,
      0,
      6345,
      [
         12697,
         "hero_item_human_warrior_hair_hair_woman_50__avatar_hair_back_lay01_c2"
      ],
      [
         12699,
         "hero_item_human_warrior_hair_hair_woman_50__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      567,
      51,
      true,
      "woman hair 51",
      "hair",
      0,
      0,
      0,
      6347,
      [
         12701,
         "hero_item_human_warrior_hair_hair_woman_51__avatar_hair_back_lay01_c2"
      ],
      [
         12703,
         "hero_item_human_warrior_hair_hair_woman_51__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      569,
      52,
      true,
      "woman hair 52",
      "hair",
      0,
      0,
      0,
      6349,
      [
         12705,
         "hero_item_human_warrior_hair_hair_woman_52__avatar_hair_back_lay01_c2"
      ],
      [
         12707,
         "hero_item_human_warrior_hair_hair_woman_52__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      571,
      53,
      true,
      "woman hair 53",
      "hair",
      0,
      0,
      0,
      6351,
      [
         12709,
         "hero_item_human_warrior_hair_hair_woman_53__avatar_hair_back_lay01_c2"
      ],
      [
         12711,
         "hero_item_human_warrior_hair_hair_woman_53__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      573,
      54,
      true,
      "woman hair 54",
      "hair",
      0,
      0,
      0,
      6353,
      [
         12713,
         "hero_item_human_warrior_hair_hair_woman_54__avatar_hair_back_lay01_c2"
      ],
      [
         12715,
         "hero_item_human_warrior_hair_hair_woman_54__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      575,
      55,
      true,
      "woman hair 55",
      "hair",
      0,
      0,
      0,
      6355,
      [
         12717,
         "hero_item_human_warrior_hair_hair_woman_55__avatar_hair_back_lay01_c2"
      ],
      [
         12719,
         "hero_item_human_warrior_hair_hair_woman_55__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      577,
      56,
      true,
      "woman hair 56",
      "hair",
      0,
      0,
      0,
      6357,
      [
         12721,
         "hero_item_human_warrior_hair_hair_woman_56__avatar_hair_back_lay01_c2"
      ],
      [
         12723,
         "hero_item_human_warrior_hair_hair_woman_56__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      579,
      57,
      true,
      "woman hair 57",
      "hair",
      0,
      0,
      0,
      6359,
      [
         12725,
         "hero_item_human_warrior_hair_hair_woman_57__avatar_hair_back_lay01_c2"
      ],
      [
         12727,
         "hero_item_human_warrior_hair_hair_woman_57__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      581,
      58,
      true,
      "woman hair 58",
      "hair",
      0,
      0,
      0,
      6361,
      [
         12729,
         "hero_item_human_warrior_hair_hair_woman_58__avatar_hair_back_lay01_c2"
      ],
      [
         12731,
         "hero_item_human_warrior_hair_hair_woman_58__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      583,
      59,
      true,
      "woman hair 59",
      "hair",
      0,
      0,
      0,
      6363,
      [
         12733,
         "hero_item_human_warrior_hair_hair_woman_59__avatar_hair_back_lay01_c2"
      ],
      [
         12735,
         "hero_item_human_warrior_hair_hair_woman_59__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      585,
      60,
      true,
      "woman hair 60",
      "hair",
      0,
      0,
      0,
      6365,
      [
         12737,
         "hero_item_human_warrior_hair_hair_woman_60__avatar_hair_back_lay01_c2"
      ],
      [
         12739,
         "hero_item_human_warrior_hair_hair_woman_60__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      587,
      61,
      true,
      "woman hair 61",
      "hair",
      0,
      0,
      0,
      6367,
      [
         12741,
         "hero_item_human_warrior_hair_hair_woman_61__avatar_hair_back_lay01_c2"
      ],
      [
         12743,
         "hero_item_human_warrior_hair_hair_woman_61__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      589,
      62,
      true,
      "woman hair 62",
      "hair",
      0,
      0,
      0,
      6369,
      [
         12745,
         "hero_item_human_warrior_hair_hair_woman_62__avatar_hair_back_lay01_c2"
      ],
      [
         12747,
         "hero_item_human_warrior_hair_hair_woman_62__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      591,
      63,
      true,
      "woman hair 63",
      "hair",
      0,
      0,
      0,
      6371,
      [
         12749,
         "hero_item_human_warrior_hair_hair_woman_63__avatar_hair_back_lay01_c2"
      ],
      [
         12751,
         "hero_item_human_warrior_hair_hair_woman_63__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      593,
      64,
      true,
      "woman hair 64",
      "hair",
      0,
      0,
      0,
      6373,
      [
         12753,
         "hero_item_human_warrior_hair_hair_woman_64__avatar_hair_back_lay01_c2"
      ],
      [
         12755,
         "hero_item_human_warrior_hair_hair_woman_64__avatar_hair_front_add_lay110"
      ],
      [
         12757,
         "hero_item_human_warrior_hair_hair_woman_64__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      595,
      65,
      true,
      "woman hair 65",
      "hair",
      0,
      0,
      0,
      6375,
      [
         12759,
         "hero_item_human_warrior_hair_hair_woman_65__avatar_hair_back_lay01_c2"
      ],
      [
         12761,
         "hero_item_human_warrior_hair_hair_woman_65__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      597,
      66,
      true,
      "woman hair 66",
      "hair",
      0,
      0,
      0,
      6377,
      [
         12763,
         "hero_item_human_warrior_hair_hair_woman_66__avatar_hair_back_lay01_c2"
      ],
      [
         12765,
         "hero_item_human_warrior_hair_hair_woman_66__avatar_hair_front_add_lay110"
      ],
      [
         12767,
         "hero_item_human_warrior_hair_hair_woman_66__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      599,
      67,
      true,
      "woman hair 67",
      "hair",
      0,
      0,
      0,
      6379,
      [
         12769,
         "hero_item_human_warrior_hair_hair_woman_67__avatar_hair_back_lay01_c2"
      ],
      [
         12771,
         "hero_item_human_warrior_hair_hair_woman_67__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      601,
      68,
      true,
      "woman hair 68",
      "hair",
      0,
      0,
      0,
      6381,
      [
         12773,
         "hero_item_human_warrior_hair_hair_woman_68__avatar_hair_back_lay01_c2"
      ],
      [
         12775,
         "hero_item_human_warrior_hair_hair_woman_68__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      603,
      69,
      true,
      "woman hair 69",
      "hair",
      0,
      0,
      0,
      6383,
      [
         14027,
         "hero_item_human_warrior_hair_hair_woman_69__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      605,
      70,
      true,
      "woman hair 70",
      "hair",
      0,
      0,
      0,
      6385,
      [
         12777,
         "hero_item_human_warrior_hair_hair_woman_70__avatar_hair_back_lay01_c2"
      ],
      [
         12779,
         "hero_item_human_warrior_hair_hair_woman_70__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      607,
      71,
      true,
      "woman hair 71",
      "hair",
      0,
      0,
      0,
      6387,
      [
         12781,
         "hero_item_human_warrior_hair_hair_woman_71__avatar_hair_back_lay01_c2"
      ],
      [
         12783,
         "hero_item_human_warrior_hair_hair_woman_71__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      609,
      72,
      true,
      "woman hair 72",
      "hair",
      0,
      0,
      0,
      6389,
      [
         12785,
         "hero_item_human_warrior_hair_hair_woman_72__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      611,
      73,
      true,
      "woman hair 73",
      "hair",
      0,
      0,
      0,
      6391,
      [
         12787,
         "hero_item_human_warrior_hair_hair_woman_73__avatar_hair_back_lay01_c2"
      ],
      [
         12789,
         "hero_item_human_warrior_hair_hair_woman_73__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      613,
      74,
      true,
      "woman hair 74",
      "hair",
      0,
      0,
      0,
      6393,
      [
         12791,
         "hero_item_human_warrior_hair_hair_woman_74__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      615,
      75,
      true,
      "woman hair 75",
      "hair",
      0,
      0,
      0,
      6395,
      [
         12793,
         "hero_item_human_warrior_hair_hair_woman_75__avatar_hair_back_lay01_c2"
      ],
      [
         12795,
         "hero_item_human_warrior_hair_hair_woman_75__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      617,
      76,
      true,
      "woman hair 76",
      "hair",
      0,
      0,
      0,
      6397,
      [
         12797,
         "hero_item_human_warrior_hair_hair_woman_76__avatar_hair_back_lay01_c2"
      ],
      [
         12799,
         "hero_item_human_warrior_hair_hair_woman_76__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      619,
      77,
      true,
      "woman hair 77",
      "hair",
      0,
      0,
      0,
      6399,
      [
         12801,
         "hero_item_human_warrior_hair_hair_woman_77__avatar_hair_back_lay01_c2"
      ],
      [
         12803,
         "hero_item_human_warrior_hair_hair_woman_77__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      621,
      78,
      true,
      "woman hair 78",
      "hair",
      0,
      0,
      0,
      6401,
      [
         12805,
         "hero_item_human_warrior_hair_hair_woman_78__avatar_hair_back_lay01_c2"
      ],
      [
         12807,
         "hero_item_human_warrior_hair_hair_woman_78__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      623,
      79,
      true,
      "woman hair 79",
      "hair",
      0,
      0,
      0,
      6403,
      [
         12809,
         "hero_item_human_warrior_hair_hair_woman_79__avatar_hair_back_lay01_c2"
      ],
      [
         12811,
         "hero_item_human_warrior_hair_hair_woman_79__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      625,
      80,
      true,
      "woman hair 80",
      "hair",
      0,
      0,
      0,
      6405,
      [
         12813,
         "hero_item_human_warrior_hair_hair_woman_80__avatar_hair_back_lay01_c2"
      ],
      [
         12815,
         "hero_item_human_warrior_hair_hair_woman_80__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      627,
      81,
      true,
      "woman hair 81",
      "hair",
      0,
      0,
      0,
      6407,
      [
         12817,
         "hero_item_human_warrior_hair_hair_woman_81__avatar_hair_back_lay01_c2"
      ],
      [
         12819,
         "hero_item_human_warrior_hair_hair_woman_81__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      629,
      82,
      true,
      "woman hair 82",
      "hair",
      0,
      0,
      0,
      6409,
      [
         12821,
         "hero_item_human_warrior_hair_hair_woman_82__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      631,
      83,
      true,
      "woman hair 83",
      "hair",
      0,
      0,
      0,
      6411,
      [
         12823,
         "hero_item_human_warrior_hair_hair_woman_83__avatar_hair_back_lay01_c2"
      ],
      [
         12825,
         "hero_item_human_warrior_hair_hair_woman_83__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      633,
      84,
      true,
      "woman hair 84",
      "hair",
      0,
      0,
      0,
      6413,
      [
         12827,
         "hero_item_human_warrior_hair_hair_woman_84__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      635,
      85,
      true,
      "woman hair 85",
      "hair",
      0,
      0,
      0,
      6415,
      [
         12829,
         "hero_item_human_warrior_hair_hair_woman_85__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      637,
      86,
      true,
      "woman hair 86",
      "hair",
      0,
      0,
      0,
      6417,
      [
         12831,
         "hero_item_human_warrior_hair_hair_woman_86__avatar_hair_back_lay01_c2"
      ],
      [
         12833,
         "hero_item_human_warrior_hair_hair_woman_86__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      639,
      87,
      true,
      "woman hair 87",
      "hair",
      0,
      0,
      0,
      6419,
      [
         12835,
         "hero_item_human_warrior_hair_hair_woman_87__avatar_hair_back_lay01_c2"
      ],
      [
         12837,
         "hero_item_human_warrior_hair_hair_woman_87__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      641,
      88,
      true,
      "woman hair 88",
      "hair",
      0,
      0,
      0,
      6421,
      [
         12839,
         "hero_item_human_warrior_hair_hair_woman_88__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      643,
      89,
      true,
      "woman hair 89",
      "hair",
      0,
      0,
      0,
      6423,
      [
         12841,
         "hero_item_human_warrior_hair_hair_woman_89__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      645,
      90,
      true,
      "woman hair 90",
      "hair",
      0,
      0,
      0,
      6425,
      [
         12843,
         "hero_item_human_warrior_hair_hair_woman_90__avatar_hair_back_lay01_c2"
      ],
      [
         12845,
         "hero_item_human_warrior_hair_hair_woman_90__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      647,
      91,
      true,
      "woman hair 91",
      "hair",
      0,
      0,
      0,
      6427,
      [
         12847,
         "hero_item_human_warrior_hair_hair_woman_91__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      649,
      92,
      true,
      "woman hair 92",
      "hair",
      0,
      0,
      0,
      6429,
      [
         12849,
         "hero_item_human_warrior_hair_hair_woman_92__avatar_hair_back_lay01_c2"
      ],
      [
         12851,
         "hero_item_human_warrior_hair_hair_woman_92__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      651,
      93,
      true,
      "woman hair 93",
      "hair",
      0,
      0,
      0,
      6431,
      [
         12853,
         "hero_item_human_warrior_hair_hair_woman_93__avatar_hair_back_lay01_c2"
      ],
      [
         12855,
         "hero_item_human_warrior_hair_hair_woman_93__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      653,
      94,
      true,
      "woman hair 94",
      "hair",
      0,
      0,
      0,
      6433,
      [
         12857,
         "hero_item_human_warrior_hair_hair_woman_94__avatar_hair_back_lay01_c2"
      ],
      [
         12859,
         "hero_item_human_warrior_hair_hair_woman_94__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      655,
      95,
      true,
      "woman hair 95",
      "hair",
      0,
      0,
      0,
      6435,
      [
         12861,
         "hero_item_human_warrior_hair_hair_woman_95__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      657,
      96,
      true,
      "woman hair 96",
      "hair",
      0,
      0,
      0,
      6437,
      [
         12863,
         "hero_item_human_warrior_hair_hair_woman_96__avatar_hair_back_lay01_c2"
      ],
      [
         12865,
         "hero_item_human_warrior_hair_hair_woman_96__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      659,
      97,
      true,
      "woman hair 97",
      "hair",
      0,
      0,
      0,
      6439,
      [
         12867,
         "hero_item_human_warrior_hair_hair_woman_97__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      661,
      98,
      true,
      "woman hair 98",
      "hair",
      0,
      0,
      0,
      6441,
      [
         12869,
         "hero_item_human_warrior_hair_hair_woman_98__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      663,
      99,
      true,
      "woman hair 99",
      "hair",
      0,
      0,
      0,
      6443,
      [
         12871,
         "hero_item_human_warrior_hair_hair_woman_99__avatar_hair_front_lay100_c2"
      ]
   ],
   [
      665,
      3,
      false,
      "woman special 03",
      "facespecial",
      0,
      0,
      0,
      6445,
      [
         12937,
         "hero_item_human_warrior_special_special_woman_03__avatar_special_lay50_c1"
      ]
   ],
   [
      667,
      5,
      false,
      "woman special 05",
      "facespecial",
      0,
      0,
      0,
      6447,
      [
         12939,
         "hero_item_human_warrior_special_special_woman_05__avatar_special_lay50_c1"
      ]
   ],
   [
      669,
      6,
      false,
      "woman special 06",
      "facespecial",
      0,
      0,
      0,
      6449,
      [
         12941,
         "hero_item_human_warrior_special_special_woman_06__avatar_special_lay50_c1"
      ]
   ],
   [
      671,
      7,
      false,
      "woman special 07",
      "facespecial",
      0,
      0,
      0,
      6451,
      [
         12943,
         "hero_item_human_warrior_special_special_woman_07__avatar_special_lay50_c1"
      ]
   ],
   [
      673,
      8,
      false,
      "woman special 08",
      "facespecial",
      0,
      0,
      0,
      6453,
      [
         12945,
         "hero_item_human_warrior_special_special_woman_08__avatar_special_lay50_c1"
      ]
   ],
   [
      675,
      9,
      false,
      "woman special 09",
      "facespecial",
      0,
      0,
      0,
      6455,
      [
         12947,
         "hero_item_human_warrior_special_special_woman_09__avatar_special_lay50_c1"
      ]
   ],
   [
      677,
      10,
      false,
      "woman special 10",
      "facespecial",
      0,
      0,
      0,
      6457,
      [
         12949,
         "hero_item_human_warrior_special_special_woman_10__avatar_special_lay50_c1"
      ]
   ],
   [
      679,
      11,
      false,
      "woman special 11",
      "facespecial",
      0,
      0,
      0,
      6459,
      [
         12951,
         "hero_item_human_warrior_special_special_woman_11__avatar_special_lay50_c1"
      ]
   ],
   [
      681,
      12,
      false,
      "woman special 12",
      "facespecial",
      0,
      0,
      0,
      6461,
      [
         12953,
         "hero_item_human_warrior_special_special_woman_12__avatar_special_top_lay95"
      ]
   ],
   [
      683,
      13,
      false,
      "woman special 13",
      "facespecial",
      0,
      0,
      0,
      6463,
      [
         12955,
         "hero_item_human_warrior_special_special_woman_13__avatar_special_top_lay95"
      ]
   ],
   [
      685,
      14,
      false,
      "woman special 14",
      "facespecial",
      0,
      0,
      0,
      6465,
      [
         12957,
         "hero_item_human_warrior_special_special_woman_14__avatar_special_lay50_c1"
      ]
   ],
   [
      687,
      15,
      false,
      "woman special 15",
      "facespecial",
      0,
      0,
      0,
      6467,
      [
         12959,
         "hero_item_human_warrior_special_special_woman_15__avatar_special_lay50_c1"
      ]
   ],
   [
      689,
      16,
      false,
      "woman special 16",
      "facespecial",
      0,
      0,
      0,
      6469,
      [
         12961,
         "hero_item_human_warrior_special_special_woman_16__avatar_special_lay50_c1"
      ]
   ],
   [
      691,
      17,
      false,
      "woman special 17",
      "facespecial",
      0,
      0,
      0,
      6471,
      [
         12963,
         "hero_item_human_warrior_special_special_woman_17__avatar_special_lay50_c1"
      ]
   ],
   [
      693,
      18,
      false,
      "woman special 18",
      "facespecial",
      0,
      0,
      0,
      6473,
      [
         12965,
         "hero_item_human_warrior_special_special_woman_18__avatar_special_lay50_c1"
      ]
   ],
   [
      695,
      19,
      false,
      "woman special 19",
      "facespecial",
      0,
      0,
      0,
      6475,
      [
         12967,
         "hero_item_human_warrior_special_special_woman_19__avatar_special_lay50_c1"
      ]
   ],
   [
      699,
      21,
      false,
      "woman special 21",
      "facespecial",
      0,
      0,
      0,
      6479,
      [
         12973,
         "hero_item_human_warrior_special_special_woman_21__avatar_special_lay50_c1"
      ]
   ],
   [
      701,
      23,
      false,
      "woman special 23",
      "facespecial",
      0,
      0,
      0,
      6481,
      [
         12975,
         "hero_item_human_warrior_special_special_woman_23__avatar_special_lay50_c1"
      ]
   ],
   [
      703,
      24,
      false,
      "woman special 24",
      "facespecial",
      0,
      0,
      0,
      6483,
      [
         12977,
         "hero_item_human_warrior_special_special_woman_24__avatar_special_lay50_c1"
      ]
   ],
   [
      705,
      26,
      false,
      "woman special 26",
      "facespecial",
      0,
      0,
      0,
      6485,
      [
         12979,
         "hero_item_human_warrior_special_special_woman_26__avatar_special_lay50_c1"
      ]
   ],
   [
      707,
      31,
      false,
      "woman special 31",
      "facespecial",
      0,
      0,
      0,
      6487,
      [
         12981,
         "hero_item_human_warrior_special_special_woman_31__avatar_special_top_lay95"
      ]
   ],
   [
      709,
      32,
      false,
      "woman special 32",
      "facespecial",
      0,
      0,
      0,
      6489,
      [
         12983,
         "hero_item_human_warrior_special_special_woman_32__avatar_special_top_lay95"
      ]
   ],
   [
      711,
      33,
      false,
      "woman special 33",
      "facespecial",
      0,
      0,
      0,
      6491,
      [
         12985,
         "hero_item_human_warrior_special_special_woman_33__avatar_special_top_lay95"
      ]
   ],
   [
      713,
      34,
      false,
      "woman special 34",
      "facespecial",
      0,
      0,
      0,
      6493,
      [
         12987,
         "hero_item_human_warrior_special_special_woman_34__avatar_special_top_lay95"
      ]
   ],
   [
      715,
      35,
      false,
      "woman special 35",
      "facespecial",
      0,
      0,
      0,
      6495,
      [
         12989,
         "hero_item_human_warrior_special_special_woman_35__avatar_special_top_lay95"
      ]
   ],
   [
      717,
      39,
      false,
      "woman special 39",
      "facespecial",
      0,
      0,
      0,
      6497,
      [
         12991,
         "hero_item_human_warrior_special_special_woman_39__avatar_special_top_lay95"
      ]
   ],
   [
      719,
      40,
      false,
      "woman special 40",
      "facespecial",
      0,
      0,
      0,
      6499,
      [
         12993,
         "hero_item_human_warrior_special_special_woman_40__avatar_special_lay50_c1"
      ]
   ],
   [
      721,
      43,
      false,
      "woman special 43",
      "facespecial",
      0,
      0,
      0,
      6501,
      [
         12995,
         "hero_item_human_warrior_special_special_woman_43__avatar_special_over_hair_lay120"
      ]
   ],
   [
      723,
      44,
      false,
      "woman special 44",
      "facespecial",
      0,
      0,
      0,
      6503,
      [
         12997,
         "hero_item_human_warrior_special_special_woman_44__avatar_special_over_hair_lay120"
      ]
   ],
   [
      725,
      45,
      false,
      "woman special 45",
      "facespecial",
      0,
      0,
      0,
      6505,
      [
         12999,
         "hero_item_human_warrior_special_special_woman_45__avatar_special_over_hair_lay120"
      ]
   ],
   [
      727,
      2,
      false,
      "woman face 02",
      "nose",
      0,
      0,
      0,
      6619,
      [
         12069,
         "hero_item_human_warrior_face_face_woman_02__avatar_face_lay20_c1"
      ]
   ],
   [
      729,
      4,
      false,
      "woman face 04",
      "nose",
      0,
      0,
      0,
      6621,
      [
         12075,
         "hero_item_human_warrior_face_face_woman_04__avatar_face_lay20_c1"
      ]
   ],
   [
      731,
      5,
      false,
      "woman face 05",
      "nose",
      0,
      0,
      0,
      6623,
      [
         12077,
         "hero_item_human_warrior_face_face_woman_05__avatar_face_lay20_c1"
      ]
   ],
   [
      733,
      6,
      false,
      "woman face 06",
      "nose",
      0,
      0,
      0,
      6625,
      [
         12079,
         "hero_item_human_warrior_face_face_woman_06__avatar_face_lay20_c1"
      ]
   ],
   [
      735,
      7,
      false,
      "woman face 06",
      "nose",
      0,
      0,
      0,
      6627,
      [
         12081,
         "hero_item_human_warrior_face_face_woman_07__avatar_face_lay20_c1"
      ]
   ],
   [
      737,
      8,
      false,
      "woman face 08",
      "nose",
      0,
      0,
      0,
      6629,
      [
         12083,
         "hero_item_human_warrior_face_face_woman_08__avatar_ears_add_lay30"
      ],
      [
         12085,
         "hero_item_human_warrior_face_face_woman_08__avatar_face_lay20_c1"
      ]
   ],
   [
      739,
      9,
      false,
      "woman face 09",
      "nose",
      0,
      0,
      0,
      6631,
      [
         12087,
         "hero_item_human_warrior_face_face_woman_09__avatar_ears_add_lay30"
      ],
      [
         12089,
         "hero_item_human_warrior_face_face_woman_09__avatar_face_lay20_c1"
      ]
   ],
   [
      741,
      10,
      false,
      "woman face 10",
      "nose",
      0,
      0,
      0,
      6633,
      [
         12091,
         "hero_item_human_warrior_face_face_woman_10__avatar_face_lay20_c1"
      ]
   ],
   [
      743,
      11,
      false,
      "woman face 11",
      "nose",
      0,
      0,
      0,
      6635,
      [
         12093,
         "hero_item_human_warrior_face_face_woman_11__avatar_face_lay20_c1"
      ]
   ],
   [
      745,
      12,
      false,
      "woman face 12",
      "nose",
      0,
      0,
      0,
      6637,
      [
         12095,
         "hero_item_human_warrior_face_face_woman_12__avatar_face_lay20_c1"
      ]
   ],
   [
      747,
      13,
      false,
      "woman face 13",
      "nose",
      0,
      0,
      0,
      6639,
      [
         12097,
         "hero_item_human_warrior_face_face_woman_13__avatar_ears_add_lay30"
      ],
      [
         12099,
         "hero_item_human_warrior_face_face_woman_13__avatar_face_lay20_c1"
      ]
   ],
   [
      749,
      14,
      false,
      "woman face 14",
      "nose",
      0,
      0,
      0,
      6641,
      [
         12101,
         "hero_item_human_warrior_face_face_woman_14__avatar_face_lay20_c1"
      ]
   ],
   [
      751,
      15,
      false,
      "woman face 15",
      "nose",
      0,
      0,
      0,
      6643,
      [
         12103,
         "hero_item_human_warrior_face_face_woman_15__avatar_face_lay20_c1"
      ]
   ],
   [
      753,
      16,
      false,
      "woman face 16",
      "nose",
      0,
      0,
      0,
      6645,
      [
         12105,
         "hero_item_human_warrior_face_face_woman_16__avatar_ears_add_lay30"
      ],
      [
         12107,
         "hero_item_human_warrior_face_face_woman_16__avatar_face_lay20_c1"
      ]
   ],
   [
      755,
      17,
      false,
      "woman face 17",
      "nose",
      0,
      0,
      0,
      6647,
      [
         12109,
         "hero_item_human_warrior_face_face_woman_17__avatar_ears_add_lay30"
      ],
      [
         12111,
         "hero_item_human_warrior_face_face_woman_17__avatar_face_lay20_c1"
      ]
   ],
   [
      757,
      18,
      false,
      "woman face 18",
      "nose",
      0,
      0,
      0,
      6649,
      [
         12113,
         "hero_item_human_warrior_face_face_woman_18__avatar_ears_add_lay30"
      ],
      [
         12115,
         "hero_item_human_warrior_face_face_woman_18__avatar_face_lay20_c1"
      ]
   ],
   [
      759,
      20,
      false,
      "woman face 20",
      "nose",
      0,
      0,
      0,
      6651,
      [
         12117,
         "hero_item_human_warrior_face_face_woman_20__avatar_face_lay20_c1"
      ]
   ],
   [
      761,
      21,
      false,
      "woman face 21",
      "nose",
      0,
      0,
      0,
      6653,
      [
         12123,
         "hero_item_human_warrior_face_face_woman_21__avatar_ears_add_lay30"
      ],
      [
         12125,
         "hero_item_human_warrior_face_face_woman_21__avatar_face_lay20_c1"
      ]
   ],
   [
      763,
      22,
      false,
      "woman face 22",
      "nose",
      0,
      0,
      0,
      6655,
      [
         12127,
         "hero_item_human_warrior_face_face_woman_22__avatar_face_lay20_c1"
      ]
   ],
   [
      765,
      23,
      false,
      "woman face 23",
      "nose",
      0,
      0,
      0,
      6657,
      [
         12129,
         "hero_item_human_warrior_face_face_woman_23__avatar_ears_add_lay30"
      ],
      [
         12131,
         "hero_item_human_warrior_face_face_woman_23__avatar_face_lay20_c1"
      ]
   ],
   [
      767,
      24,
      false,
      "woman face 24",
      "nose",
      0,
      0,
      0,
      6659,
      [
         12133,
         "hero_item_human_warrior_face_face_woman_24__avatar_ears_add_lay30"
      ],
      [
         12135,
         "hero_item_human_warrior_face_face_woman_24__avatar_face_lay20_c1"
      ]
   ],
   [
      769,
      26,
      false,
      "woman face 26",
      "nose",
      0,
      0,
      0,
      6719,
      [
         12139,
         "hero_item_human_warrior_face_face_woman_26__avatar_face_lay20_c1"
      ]
   ],
   [
      771,
      25,
      false,
      "woman face 25",
      "nose",
      0,
      0,
      0,
      6717,
      [
         12137,
         "hero_item_human_warrior_face_face_woman_25__avatar_face_lay20_c1"
      ]
   ],
   [
      773,
      19,
      false,
      "woman face 19",
      "nose",
      0,
      0,
      0,
      6715,
      [
         12119,
         "hero_item_human_warrior_face_face_woman_19__avatar_ears_add_lay30"
      ],
      [
         12121,
         "hero_item_human_warrior_face_face_woman_19__avatar_face_lay20_c1"
      ]
   ],
   [
      775,
      3,
      false,
      "woman face 03",
      "nose",
      0,
      0,
      0,
      6713,
      [
         12071,
         "hero_item_human_warrior_face_face_woman_03__avatar_ears_add_lay30"
      ],
      [
         12073,
         "hero_item_human_warrior_face_face_woman_03__avatar_face_lay20_c1"
      ]
   ],
   [
      777,
      16,
      false,
      "woman eyes 16",
      "eyes",
      0,
      0,
      0,
      6743,
      [
         11991,
         "hero_item_human_warrior_eyes_eyes_woman_16__avatar_eyes_lay40"
      ]
   ],
   [
      779,
      17,
      false,
      "woman eyes 17",
      "eyes",
      0,
      0,
      0,
      6745,
      [
         11993,
         "hero_item_human_warrior_eyes_eyes_woman_17__avatar_eyes_lay40"
      ]
   ],
   [
      781,
      18,
      false,
      "woman eyes 18",
      "eyes",
      0,
      0,
      0,
      6747,
      [
         11995,
         "hero_item_human_warrior_eyes_eyes_woman_18__avatar_eyes_lay40"
      ]
   ],
   [
      783,
      19,
      false,
      "woman eyes 19",
      "eyes",
      0,
      0,
      0,
      6749,
      [
         11997,
         "hero_item_human_warrior_eyes_eyes_woman_19__avatar_eyes_lay40"
      ]
   ],
   [
      785,
      20,
      false,
      "woman eyes 20",
      "eyes",
      0,
      0,
      0,
      6751,
      [
         11999,
         "hero_item_human_warrior_eyes_eyes_woman_20__avatar_eyes_lay40"
      ]
   ]
]
